### ISSUE TITLE
Arrows-Section is imcomplete

### ISSUE THREAD

**Issue by ehhc** [TobseF/boostnote-markdown-cheatsheet#1]
If you enable it in the settings `Interface > Preview > Convert textual arrows to beautiful signs. ⚠ This will interfere with using HTML comments in your Markdown.` some textual arrows will be converted to beautiful ones (it is done by https://github.com/adam-p/markdown-it-smartarrows) therefore the following arrows work: 
--> →
<-- ←
<--> ↔
==> ⇒
<== ⇐
<==> ⇔

**Comment by TobseF** [comment]
Thank you for this hint. I thought the arrows are done by [ligatures](https://en.wikipedia.org/wiki/Typographic_ligature) feature of the [FiraCode](https://github.com/tonsky/FiraCode/) font. But that was wrong. I've added your example to the cheat sheet.
