### ISSUE TITLE
"raw" mode of cheatsheet uses github markdown

### ISSUE THREAD

**Issue by hinder90** [TobseF/boostnote-markdown-cheatsheet#4]
Trying to view the "code" of the cheatsheet does *not* show you the raw code as you would view in the Boostnote Editor as the github markdown parser interpolates that markdown symbols make it a jumbled mess. Furthermore, trying to copy and paste the raw text of the "code" cheatsheet doesn't render properly in Boostnote either (which honestly would make the most sense) because there are many places where the markdown code has been slashed-out so it renders literally in preview. The result is another different jumbled mess. Looking at the raw text it appears that some of the markdown is clearly intended to not be interpolated, but a lot of it which I'd have expected to be also be (such as the rudimentary emphasis code) is clearly meant to be interpolated- why, I have no idea. It's what I would call a "mish-mash". I don't one can disable MDE for a block of text in github if that is at all possible, but it's clear that trying to escape every single markdown token is a nightmare. I honestly am not sure what the intent of the "cheatsheet" mode is even for if it is clearly not intended to show the code.

It might just be easiest to write the cheatsheet in a manner that is just be pasted in Boostnote so you just have the cheatsheet in in your notes and see _exactly_ how it will be rendered because... _that's what's doing the interpolation!_ Honestly, I am not sure why a comprehensive cheatsheet isn't included with the example documents in the first place as one of the starter docs since the guide has zero markdown tips. I don't get this at all.

**Comment by TobseF** [comment]
Yes you are right... the intention of the cheat sheet is to easily copy paste it to Boostnote.

There is one little trick to copy & paste it without escaping:
1. Open the _raw_ file and press <kbd>ctrl</kbd>+<kbd>a</kbd>, <kbd>ctrl</kbd>+<kbd>c</kbd>
[BOOSTNOTE_MARKDOWN_CHEAT_SHEET.md](https://raw.githubusercontent.com/TobseF/boostnote-markdown-cheatsheet/master/BOOSTNOTE_MARKDOWN_CHEAT_SHEET.md)
2. Switch to Boostnote an paste it with <kbd>ctrl</kbd>+<kbd>shift</kbd>+<kbd>v</kbd>
The additional <kbd>shift</kbd> ensures that nothing gets escaped.

Maybe I should add this paste hint also to the notes.
I'am happy that my cheat sheet is linked in the Boostnote menu:
_Help > Cheat Sheets > Boostnote_
Adding it as sample page for a fresh installation would be also great.

**Comment by TobseF** [comment]
I added a "_How to add it to Boostenote_" section to the beginning of the cheat sheet. So the usage should be clearer.
