### ISSUE TITLE
update links: 404

### ISSUE THREAD

**Issue by arcturus140** [TobseF/boostnote-markdown-cheatsheet#8]
Examples use a png from the Boostnote.io website which no longer exist. Therefore demo is broken.

Replace `https://boostnote.io/assets/img/logo.png` with `https://boostnote.io/static/images/logo_with_text_teal.svg`

**Comment by TobseF** [comment]
Thanks for the hint.
Updated the image URL:
https://github.com/TobseF/boostnote-markdown-cheatsheet/commit/76da2520126884d098cd08d40e7a5eb0327a276e
