### ISSUE TITLE
Boost Note Version

### ISSUE THREAD

**Issue by AlbertMontagutCasero** [TobseF/boostnote-markdown-cheatsheet#9]
Which version do you use for the project?

I am currently using the Windows desktop version 0.16.1(2020.9.5) but I can't see the results as you showed.

## Your
![imagen](https://user-images.githubusercontent.com/23361386/95778537-9e137580-0cc8-11eb-9240-86027b85550a.png)

## Mine
![imagen](https://user-images.githubusercontent.com/23361386/95778417-5ee52480-0cc8-11eb-99e2-46344646a7a4.png)

**Comment by TobseF** [comment]
Double check, that you insert it without escaping:

**:information_source: How to insert it into Boostenote**
1. Open the [RAW](https://raw.githubusercontent.com/TobseF/boostnote-markdown-cheatsheet/master/BOOSTNOTE_MARKDOWN_CHEAT_SHEET.md) version of the cheat sheet. 
2. Copy it with <kbd>crtl</kbd> + <kbd>a</kbd> and <kbd>crtl</kbd> + <kbd>c</kbd>
3. Create an empty _Markdown Note_ in Bosstnote paste it with  
   <kbd>crtl</kbd> + <kbd>shift</kbd> + <kbd>v</kbd>  
   (The *shift* is important to skip escaping)

Respecting that, the _Diagram_ snippets work on Boostnote version `0.16.1(2020.9.5)`.

**Comment by AlbertMontagutCasero** [comment]
I'm sorry, I've done exactly this, but it is not working anyway. I can record a video if you want, but it is not working.
